[advisories]
ignore = [
    "RUSTSEC-2023-0071", # Marvin Attack (RSA) - Unused dependency (we use Postgres, coming from sqlx-mysql)
    "RUSTSEC-2025-0134", # rustls-pemfile unmaintained - Transitive dependency, warning only
]
