services:
  db:
    image: postgres:16-alpine
    container_name: petpulse_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petpulse
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: petpulse_redis
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: petpulse_server
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/petpulse
      REDIS_URL: redis://redis:6379
      RUST_LOG: "debug,petpulse_server=debug,sqlx=warn,sea_orm=warn,tower_http=debug,axum=debug,multipart=debug"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
      GEMINI_MODEL: "gemini-2.5-flash"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      RUST_LOG_FORMAT: json
      AGENT_SERVICE_URL: http://agent:3002/alert
    volumes:
      - ./clestiq-petpulse-6b40f17a955d.json:/app/credentials.json
    depends_on:
      - db
      - redis
      - tempo
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/server

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: petpulse_worker
    environment:
      DATABASE_URL: postgres://user:password@db:5432/petpulse
      REDIS_URL: redis://redis:6379
      RUST_LOG: "info,petpulse_server=debug,sqlx=warn,sea_orm=warn"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
      GEMINI_MODEL: "gemini-2.5-flash"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      RUST_LOG_FORMAT: json
      AGENT_SERVICE_URL: http://agent:3002/alert
    volumes:
      - ./clestiq-petpulse-6b40f17a955d.json:/app/credentials.json
    depends_on:
      - db
      - redis
      - tempo
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/worker

  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: petpulse_agent

    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/petpulse
      REDIS_URL: redis://redis:6379
      RUST_LOG: "info,petpulse_agent=debug,sqlx=warn,sea_orm=warn"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
      GEMINI_MODEL: "gemini-2.5-flash"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      RUST_LOG_FORMAT: json
    volumes:
      - ./clestiq-petpulse-6b40f17a955d.json:/app/credentials.json
    depends_on:
      - db
      - redis
      - tempo
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/agent

  # Observability
  loki:
    image: grafana/loki:3.2.0
    container_name: petpulse_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./observability/loki.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.2.0
    container_name: petpulse_promtail
    volumes:
      - ./observability/promtail.yaml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yaml

  tempo:
    image: grafana/tempo:2.6.0
    container_name: petpulse_tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./observability/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # Tempo HTTP
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP

  prometheus:
    image: prom/prometheus:latest
    container_name: petpulse_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: petpulse_grafana
    ports:
      - "3001:3000"
    volumes:
      - ./observability/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./observability/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./observability/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

volumes:
  postgres_data:
