global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "petpulse-server"
    static_configs:
      - targets: ["server:3000"]
    metrics_path: /metrics

  - job_name: "petpulse-worker"
    static_configs:
      - targets: ["worker:9091"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
